<?php

namespace AppBundle\Repository;

/**
 * createdAtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class createdAtRepository extends \Doctrine\ORM\EntityRepository
{
}
