imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    photo_directory: '%kernel.project_dir%/web/uploads'

framework:
    esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: fr
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
#        driver: pdo_sqlite
#        path: '%kernel.project_dir%/app/sqlite.db'

        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        post_image:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/web/uploads'
            # namer: vich_uploader.namer_uniqid
            namer:
              service: vich_uploader.namer_property
              options: { property: 'renameFile'}

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        item_image:

            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/web/uploads/'
            namer: vich_uploader.namer_uniqid

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
easy_admin:
    site_name: 'toto'
    design:
        brand_color: 'red'
        menu:
          - {'route': 'homepage', label: 'Accès public'}
          - {'entity': 'Propositions', label: 'Propositions', 'icon': 'tag'}
          - {'entity': 'ItemCategory', label: 'ItemCategory', 'icon': 'tag'}
          - {'entity': 'Post', label: 'Post', 'icon': 'tag'}
    entities:
        Propositions:
          class: AppBundle\Entity\Item
          form:
            fields:
              - titre
              - {property: 'image', type: 'vich_image', data_class: null}
              - itemCategory
              - url_video
          list:
            fields:
              - titre
              - itemCategory
              - {property: 'imageName', type: 'image', base_path: '/uploads/'}
        ItemCategory:
          class: AppBundle\Entity\ItemCategory
          list:
            fields:
              - titre
          form:
            fields:
              - { property: 'titre', type: 'textarea'}

        User:
          class: AppBundle\Entity\User
          form:
            fields:
              - username
              - email
              - enabled
              - lastLogin
              # if administrators are allowed to edit users' passwords and roles, add this:
              - { property: 'plainPassword', type: 'text', type_options: { required: false } }
              - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

          #    - {property: 'roles', type: 'choice', choices: [ 'ROLE_USER', 'ROLE_ADMIN']}
        Post:
          class: AppBundle\Entity\Post
          list:
            fields:
              - title
              - {property: 'imageName', type: 'image', base_path: '/uploads/'}
              - content
          form:
            fields:
              - { property: 'title', type: 'textarea'}
              - { property: 'photo', type: 'vich_image', data_class: null}
              - { property: 'content', type: 'textarea'}

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        noreply@example.com
        sender_name:    Demo App
    user_class: AppBundle\Entity\User

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
